### ISSUE TITLE
Color palettes

### ISSUE THREAD

**Issue by alduxvm** [groupgets/pylepton#12]
Hi!

This is not really an issue, but its a question, is there a way of using color palettes similar to the ones in https://github.com/groupgets/LeptonModule/blob/master/software/raspberrypi_video/Palettes.cpp ??

Thanks!

**Comment by kekiefer** [comment]
One way would be to run it through OpenCV's LUT:
http://docs.opencv.org/2.4/modules/core/doc/operations_on_arrays.html#lut

See here for an example:
http://stackoverflow.com/a/37656779

**Comment by alduxvm** [comment]
Good point, I forgot about that... I end up using this: `cv2.applyColorMap(gray, cv2.COLORMAP_JET)`

Original: 
![orig](https://cloud.githubusercontent.com/assets/8823379/26173667/b50b63d4-3b1a-11e7-8ca1-e6e0f4138904.jpg)

After the applyColorMap:
![jet](https://cloud.githubusercontent.com/assets/8823379/26173685/c2b2e85e-3b1a-11e7-95dc-751e1d67cf4d.jpg)

Thanks!

**Comment by kekiefer** [comment]
Sweet!
