### ISSUE TITLE
Using Lepton3

### ISSUE THREAD

**Issue by hjpagan** [groupgets/pylepton#14]
Hello, I was using pylepton to power my Lepton but have since bought he new Lepton3 sensor and put it on my current raspberry pi 3 setup. I am trying to understand how to update pylepton for it to work with the Lepton3. I pulled the branch with Lepton3 changes and when I run the pylepton_overlay example it seems to be using Lepton.py and not Lepton3.py to execute. This causes jitter and a weird flashing in the overlay which I assume is from the lack of buffer size for the new Lepton3. I am new to python so this is why I am feeling lost, I have been reading different sources but still can't figure it out.

Can someone point me in the right direction so I can get the Lepton3 working correctly using pylepton?

Thank you!

**Comment by kekiefer** [comment]
Until recently, the overlay example didn't try to use the Lepton3 module. A user contributed #18 which basically integrates this module, but don't expect flawless performance out of it.
