### ISSUE TITLE
How to change settings ?

### ISSUE THREAD

**Issue by shubham7jadhav** [groupgets/pylepton#16]
I have raspberry pi 3, Flir Lepton 3.0  and Lepton thermal camera Breakout board v1.4.

Before capture thermal images, I need to enable Radiometry Mode, need to enable FFC as automatic, need to enable Telemetry Mode as header using Python.
Can anybody help me to do this?

**Comment by kekiefer** [comment]
pylepton doesn't support sending CCI commands at this time.

You could use ctypes to integrate functions from the SDK. A user on the FLIR Lepton group has done it this way: https://groups.google.com/forum/#!topic/flir-lepton/i8rq6g7wZuQ
