### ISSUE TITLE
installing help?

### ISSUE THREAD

**Issue by dvaisler** [groupgets/pylepton#20]
I know this might be a silly question, but I am new to python and the Lepton..
Can anyone help with installing the Pylepton library? Not really sure what files I need to download and  how to get it working in Python.
Any help will be much appreciated

**Comment by junkert** [comment]
@dvaisler try downloading the whole repository to your system where you have the Lepton sensor installed. You will need git to checkout the PyLepton library:

```
git clone git@github.com:groupgets/pylepton.git
or
git clone https://github.com/groupgets/pylepton.git
```
