### ISSUE TITLE
Lepton Modes

### ISSUE THREAD

**Issue by anjomshoaa** [groupgets/pylepton#3]
Hi, 

I have a question about Lepton modes. Is it possible to enable/disable the Radiometry and AGC modes via pylepton? 

Thanks 
Amin

**Comment by kekiefer** [comment]
As it stands, no. Pylepton currently makes no attempts to configure or interrogate the part over i2c, which would be required to enable these different modes. There is nothing stopping it from being able to do i2c configuration, however, so pull requests are welcome!

**Comment by anjomshoaa** [comment]
Thanks for the quick reply. 

Regards
Amin
