### ISSUE TITLE
Couldn't run pylepton on a PC

### ISSUE THREAD

**Issue by ziedReg** [groupgets/pylepton#32]
Hi, i have a Mini PC with Linux Mint and i was trying to run this module but it doesn't seem to work because i need something called spidev and after some research it appears that it's something related to Raspberry Pi.

My goal is to get the temperature from the images. Is it possible to achieve this with my configuration?

**Comment by kekiefer** [comment]
spidev is not raspberry pi specific. It is a Linux kernel module. Your distro will have to have this either compiled into the kernel or available as a module, and your system will have to have the spi hardware backing it. If you have these things, then you could use pylepton and the breakout board.

If you don't, you might have better luck with a purethermal module. In this case you just need a USB port.
