### ISSUE TITLE
 Inappropriate ioctl for device

### ISSUE THREAD

**Issue by tigonza** [groupgets/pylepton#35]
I'm trying to capture the feed from a lepton 3.5, I can get image feed from the getThermal app, so I thought I'd be able to use this library to easily get snapshots from the camera. Im currently using fedora 30 on a lenovo notebook(not a rasp).
 
The error Im getting relates to the ioctl for the device:

Traceback (most recent call last):
  File "/usr/local/bin/pylepton_capture", line 37, in <module>
    image = capture(flip_v = options.flip_v, device = options.device)
  File "/usr/local/bin/pylepton_capture", line 9, in capture
    with Lepton(device) as l:
  File "/usr/local/lib/python3.7/site-packages/pylepton/Lepton.py", line 86, in __enter__
    ioctl(self.__handle, SPI_IOC_RD_MODE, struct.pack("=B", Lepton.MODE))
OSError: [Errno 25] Inappropriate ioctl for device

Ive gotten the values for SPI_IOC_RD_MODE, SPI_IOC_WR_MODE, SPI_IOC_MAGIC, which are:
SPI_IOC_RD_MODE: 2147576577  
SPI_IOC_WR_MODE: 1073834753
SPI_IOC_MAGIC: 107

Are maaybe the values wrong? or is it failing cause of a certain permission issue?
Really hoping to be able to use this library, Ill try using ubuntu (or another debian based OS) and come back with results. Hoping for a way to get pushed into the right direction to solve this. Thanks in advance.

**Comment by kekiefer** [comment]
For a purethermal board, you should take a look at some of the examples here https://github.com/groupgets/purethermal1-uvc-capture

pylepton is only for the breakout board.
