### ISSUE TITLE
Radiometric capture

### ISSUE THREAD

**Issue by zoltanszalontay** [groupgets/pylepton#42]
Can anyone tell me if pylepton can capture radiometric 14 bit arrays from the camera SPI interface that contains temperature*1000 values for 160x120 pixels? 

Also, does it support 160x120 resolution?

Thx,
Zoltán

**Comment by kekiefer** [comment]
Yes, that's what the `capture()` function returns. You can use the lepton3 or lepton3-dev branch for lepton 3 support.

**Comment by zoltanszalontay** [comment]
Thanks!
