### ISSUE TITLE
Lepton 2.5 radiometry

### ISSUE THREAD

**Issue by nitindantu** [groupgets/pylepton#47]
I would like to know how to get per pixel temperature. From what capture() function is returning, all the elements in the array are almost 30.000 all the time, irrespective of the temperature. Please tell me a way to get per pixel temperature. Thank you

**Comment by kekiefer** [comment]
Looks like this question was answered over on the google group: https://groups.google.com/forum/#!topic/flir-lepton/CDRYyaQlJJU

**Comment by nitindantu** [comment]
Yes, thank you
