### ISSUE TITLE
Program gets stuck on garbage frame detection.

### ISSUE THREAD

**Issue by SalahAssana** [groupgets/pylepton#5]
When I tried running the program it gets stuck on line 156 of Lepton.py and I'm not sure why. It was working a minute ago, but now it just keeps detecting all readings as garbage frames.

**Comment by junkert** [comment]
I have the same issue.

**Comment by junkert** [comment]
This happens when the SPI device is not responding. Maybe a better error message could be used here.

**Comment by Yemen4u2** [comment]
There is no error message. The only way I even detected this was by putting a bunch of `print` statement in my code and finding where the code got stuck.

**Comment by larryfkm** [comment]
Is there any way to reset and recover from this situation instead of getting stuck forever here?

**Comment by hanhanhankim** [comment]
I have this issue also--any fix yet?

**Comment by kekiefer** [comment]
There was some advice on google groups on how to get LEP_RunOemReboot working through python (due to the lack of a python i2c/cci command processor in this project). https://groups.google.com/forum/#!msg/flir-lepton/aUU_F_iswlE/xSil-2XdBAAJ

It would be great to incorporate something like this into pylepton if it could be built easily.

**Comment by phishstang65** [comment]
I am getting this same issue. Has anyone tried putting VIN on a Raspberry Pi 3.3V GPIO and toggled the GPIO to reset the Lepton when this condition occurs?

**Comment by david-ra** [comment]
The same issue Here. Im using RPI3 with pylepton v3. This is the output of the console:

$ pylepton_capture out.png
Garbage frame number resetting...
Garbage frame number resetting...
Garbage frame number resetting...
Garbage frame number resetting...
Garbage frame number resetting...

I attach a image of the breackboard scorpio v7 ( without mosi pin, i dont know why ):
![20180228_105759](https://user-images.githubusercontent.com/4061951/36791561-f56fc42c-1c76-11e8-8bb2-516e6b935e63.jpg)

**Comment by david-ra** [comment]
Problem solved. Just a cable problem in the GPIO :P

**Comment by rmnd0** [comment]
> Problem solved. Just a cable problem in the GPIO :P

To wich GPIO pin did you connect CS?

**Comment by rmnd0** [comment]
Hardware:
> Rpi zero w.
> FLIR Lepton breakout board.
> FLIR Radiometric Lepton 3.5.

Software:
> Raspbian Stretch.

GPIO pinout:
CS -> Pin 24, CE0
MOSI -> Pin 19, MOSI
MISO -> Pin 21, MISO
CLK -> Pin 23, CLK
GND -> Pin 6, GND
VIN -> Pin 1, 3V3
SDA -> Pin 3, SDA
SCL -> Pin 5, SCL

It doesn't matter if using lepton3 or lepton3-dev,  the output of pylepton_capture is always "Garbage frame number resetting...".

I'm running out of ideas before I declare the thermal core broken.

Any thoughts?

Thank you.

**Comment by david-ra** [comment]
I strongly recommend to use the pure thermal 2 module :)

**Comment by rmnd0** [comment]
I might try that, thanks ;)

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by TinManAkshay** [comment]
Hi,

As i have seen people posting here about black images and garbage frame detection.

When i run pylepton_overlay -a 255 example, I get black images. I am using Lepton 3 and breakout out board v2. I have not found the cause of these black images. Any help would be highly appreciated if anyone has fixed the issue so far.

Thanks,
Akshay

**Comment by AF079** [comment]
Hi all,
Any solutions for "Program gets stuck on garbage frame detection" and/or the camera just not sending frames after a certain amount of time?

Thanks
