### ISSUE TITLE
How to find the device name like '/dev/..' when connected directly in mac?

### ISSUE THREAD

**Issue by varunmannam** [groupgets/pylepton#50]
Hi, 

I was testing in mac the example python code and there was a line that says device name: device  = '/dev/spidev0.0/' 
with Lepton(device) as l:
    a,_ = l.capture()

**In this code, how to find the USB device name as /dev/...?** 
I can see the device in the USB section of mac. 
PureThermal (fw:v1.3.0)@14420000  <class AppleUSBDevice, id 0x100002d64, registered, matched, active, busy 0 (5 ms), retain 16>
      |         "PortNum" = 2
      |         "USB Serial Number" = "00180033-5119-3138-3931-383900000000"

I can use the GUI in mac to see the thermal images, but I want to save the raw data. Can someone please help me to find this device name in the mac? 

Do we need any other Arduino/beagle/Raspberry PI board to connect this pure thermal?
Thanks.

**Comment by kekiefer** [comment]
This library is for the breakout board (SPI) and not for the purethermal boards (USB). You will find the python examples in https://github.com/groupgets/purethermal1-uvc-capture applicable to your use case.
