### ISSUE TITLE
Lepton3/3.5 using pylepton 

### ISSUE THREAD

**Issue by TinManAkshay** [groupgets/pylepton#54]
Hi,

Does anybody try to get lepton 3 or 3.5 successfully working with these libraries. What changes in the libraries could be required to get lepton 3 working? 

We are trying to switch from lepton 2.5 to 3/3.5 for better thermal imaging.

Please let me know.

**Comment by kekiefer** [comment]
You should check out the code on the `lepton3` or `lepton3-dev` branches that wil lwork with the lepton 3/3.5

**Comment by TinManAkshay** [comment]
Hi @kekiefer, 

I wanted to ask a quick question. Have you ever got lepton 3 or 3.5 fully working with these branches lepton3 or lepton3-dev using Breakout board v2.0? I'd appreciate the information.

Thanks,
Akshay

**Comment by kekiefer** [comment]
Yes. Both 3.0 and 3.5 worked with this code at least at the time those were developed.

**Comment by TinManAkshay** [comment]
Hi @kekiefer,

Can you please tell me the reason behind the **frequent thermal camera shuttering** as I believe it could be because of sync with the SPI protocol between Lepton and Pi? 

Thanks,
Akshay

**Comment by Tylersuard** [comment]
@TinManAkshay I have that same thing

**Comment by TinManAkshay** [comment]
Hi @Tylersuard  - 

Have you ever got lepton 3 or 3.5 working properly with pylepton libraries with no issues?

**Comment by Tylersuard** [comment]
@TinManAkshay no I did not, I think I just ended up using a 3rd party software, tCam mini.  https://groupgets.com/manufacturers/danjuliodesigns-llc/products/tcam-mini
