### ISSUE TITLE
"failed to get a buffer from the pool"

### ISSUE THREAD

**Issue by jan-novak** [groupgets/pylepton#9]
Hi,

when I run pylepton_overlay I'm getting error message "PiCameraRuntimeError: failed to get a buffer from the pool"

Pylepton_capture works well, raspistill -o image.jpg is working too.

any advice?

Thanks!

**Comment by kekiefer** [comment]
Did you solve this problem?

**Comment by jan-novak** [comment]
Unfortunately I did not solve it, I bought http://www.flir.com/suas/duo/
